twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        geoapify_api_key: '%env(GEOAPIFY_API_KEY)%'

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig']
